# Generated by Django 3.2.25 on 2024-07-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_voetbalspelers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voetbalspelers',
        ),
    ]
